### ISSUE TITLE
可以把前端也打包进镜像吗

### ISSUE THREAD

**Issue by Guyao146** [fslongjin/TextRecon#2]
我想在自己服务器上部署用，但是发现没有前端页面，没法在浏览器访问

**Comment by fslongjin** [comment]
用于提供对外服务的前后端是没有开源的。开源版本是为了方便大家在自己电脑上面自用，确保数据本地化，而不是对外服务。所以要用的话，部署到自己的电脑上就好咯。

没有开源前后端是出于数据安全的考量，我担心太多人把这个部署到服务器上面提供对外服务，造成其他人的论文数据泄露，从而造成很不好的影响。

目前线上版本的服务端，某种程度上，其实是以我个人在做各种开源的信誉做担保，保证我不会泄露任何数据哈哈哈。

**Comment by Guyao146** [comment]
不开源的话可以把前端也打包进镜像中吗，因为我想自己搭服务器用，windows的docker还是用着不太顺手，linux的又只部署在服务器上，这样我自己用，不向其他人提供服务，也可以你添加服务器IP限制之类的

**Comment by fslongjin** [comment]
hahahha那个前端是跟对应的后端绑定的。你可以这样：服务器运行镜像起来之后，修改check.py里面的url，改为你服务器的地址的就行。

那么本机就能使用check.py去检测了

**Comment by Guyao146** [comment]
我部署一下试一下昂，非常感谢
