### ISSUE TITLE
Docker镜像构建问题

### ISSUE THREAD

**Issue by Guyao146** [fslongjin/TextRecon#3]
系统 win11 WorkStationPro
Docker版本 win 4.30.0
日志
PS TextRecogn-main> docker build -t loooongjin/text_recogn:ernie3-nano .
ERROR: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": context canceled
经过
输入命令后长时间无响应，CTRL+C后报错

**Comment by fslongjin** [comment]
这是网络问题
