### ISSUE TITLE
doc输出无法打开

### ISSUE THREAD

**Issue by Guyao146** [fslongjin/TextRecon#4]
![image](https://github.com/fslongjin/TextRecogn/assets/61780021/330481a2-3986-461b-8ef6-095965a051e8)
日志中一切正常，但文件只有1kb,然后打不开...

**Comment by fslongjin** [comment]
这个应该是check.py对返回的错误码没有正确处理的结果。

产生这个错误的原因，大概率是这个Word文档的格式在python那个解析库里面解析时候出错了。目前，我的解决方案就是新建一个Word文档，然后把原来的内容粘贴进去（选择只粘贴文本

**Comment by Guyao146** [comment]
ok，在check.py里打开DEBUG以后看了一下，请求我网站显示404，不知道哪里出问题了

**Comment by Guyao146** [comment]
重启docker以后就可以用了，不知道是哪里的问题，可能是前面我docker进程开太多了，感谢

**Comment by Guyao146** [comment]
对了，顺便问一下，这个项目可以做改动、一键部署包、教程之类的吗，不会用作商业用途，保持原来的OS广告，如果对源码有改动保持与主仓库一样的开源协议
