### ISSUE TITLE
LFS带宽不够，模型无法下载

### ISSUE THREAD

**Issue by snakexgc** [fslongjin/TextRecon#8]
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/fslongjin/TextRecogn.git/info/lfs'
```
LFS说克隆时带宽不够，不能下载，希望能够将模型上传到云盘之类的分享一下。

**Comment by Mabbs** [comment]
> ```
> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> Failed to fetch some objects from 'https://github.com/fslongjin/TextRecogn.git/info/lfs'
> ```
> 
> LFS说克隆时带宽不够，不能下载，希望能够将模型上传到云盘之类的分享一下。

其实回退到上一个版本里面包含不是lfs的模型：
https://github.com/fslongjin/TextRecogn/raw/76c7a78ba8f1209dfd9fe937542c7aead0870f4a/model/pytorch_model.bin

**Comment by snakexgc** [comment]
> > ```
> > batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> > Failed to fetch some objects from 'https://github.com/fslongjin/TextRecogn.git/info/lfs'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > LFS说克隆时带宽不够，不能下载，希望能够将模型上传到云盘之类的分享一下。
> 
> 其实回退到上一个版本里面包含不是lfs的模型： https://github.com/fslongjin/TextRecogn/raw/76c7a78ba8f1209dfd9fe937542c7aead0870f4a/model/pytorch_model.bin

好的

**Comment by liuqingyao11** [comment]
请问您解决了这个问题？目前我点这个链接https://github.com/fslongjin/TextRecogn/raw/76c7a78ba8f1209dfd9fe937542c7aead0870f4a/model/pytorch_model.bin能下载pytorch_model.bin文件，但model文件夹下其他文件还是不知道该怎么下载。
